modLoader = "javafml"
loaderVersion = "[1,)"

[[mods]]
modId = "sagadyssey"
version = "${mod_version}"
displayName = "Sagadyssey"
description = "${mod_description}"
authors = "jgeted, T"

[[dependencies.sagadyssey]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sagadyssey]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"
